name    'deduktiva-abt'
version '0.1.0'
source 'UNKNOWN'
author 'deduktiva'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/apache', '>= 1.1.1'
dependency 'puppetlabs/postgresql', '>= 3.3.3'
