#!/bin/bash
# SessionStart hook for Claude Code on the web.
#
# The sandbox has no container runtime, so we install FOP natively from
# Debian packages and point fop.binary_path at bin/abt-fop directly
# (via a local settings override) instead of the containerized
# bin/abt-fop-container wrapper that other environments use.
set -euo pipefail

# Only run inside the remote sandbox; local dev should use bin/setup-fop.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "$CLAUDE_PROJECT_DIR"

echo "== Installing system packages (fop, saxon, java-wrappers) =="
export DEBIAN_FRONTEND=noninteractive
if ! dpkg -s fop libsaxonb-java java-wrappers openjdk-21-jre-headless >/dev/null 2>&1; then
  # Disable broken third-party PPAs that block apt-get update in the sandbox.
  for f in /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
    [ -e "$f" ] || continue
    case "$f" in
      *deadsnakes*|*ondrej*) mv "$f" "$f.disabled" ;;
    esac
  done
  apt-get update -qq
  apt-get install -y -qq --no-install-recommends \
    fop \
    libsaxonb-java \
    java-wrappers \
    openjdk-21-jre-headless
fi

echo "== Installing Ruby gems =="
bundle install --quiet

echo "== Seeding config/database.yml from sample (if missing) =="
if [ ! -f config/database.yml ]; then
  cp config/database.yml.sample config/database.yml
fi

echo "== Verifying chromium for system tests =="
# BROWSER_PATH is set in .claude/settings.json to the version-stable
# Playwright chromium symlink; we just sanity-check it here.
if [ -x "${BROWSER_PATH:-/opt/pw-browsers/chromium}" ]; then
  "${BROWSER_PATH:-/opt/pw-browsers/chromium}" --version
else
  echo "WARNING: chromium not found at ${BROWSER_PATH:-/opt/pw-browsers/chromium} — system tests will fail until BROWSER_PATH is fixed."
fi

echo "== Configuring native FOP via settings overrides =="
# Point fop.binary_path at the canonical launcher; the tracked dev/test
# settings default to ./bin/abt-fop-container which requires podman/docker.
mkdir -p config/settings
for env in development test; do
  cat > "config/settings/${env}.local.yml" << YAML
# Generated by .claude/hooks/session-start.sh — runs FOP natively because
# the Claude Code sandbox has no container runtime. Safe to delete if you
# install podman/docker and build the abt-fop image.
fop:
  binary_path: "./bin/abt-fop"
YAML
done

echo "== Verifying FOP launcher =="
./bin/abt-fop -version

echo "== FOP setup complete =="

echo "== Installing superpowers plugin =="
claude plugin marketplace add obra/superpowers-marketplace
claude plugin install superpowers@superpowers-marketplace
