# The trix toolbar icon masks in actiontext.scss take their SVG path data
# from the bootstrap-icons gem so they can't drift from the icon set
# action_icon/nav_icon use. Dart Sass can't run Ruby, so this task
# materialises the map as a generated partial before every dartsass build.
namespace :dartsass do
  task :generate_trix_icon_shapes do
    require "bootstrap_icons"

    icon_names = {
      "bold" => "type-bold",
      "italic" => "type-italic",
      "heading-1" => "type-h1",
      "bullet-list" => "list-ul",
      "number-list" => "list-ol",
      "undo" => "arrow-counterclockwise",
      "redo" => "arrow-clockwise"
    }

    scss = +"// Generated by rails dartsass:generate_trix_icon_shapes — do not edit.\n"
    scss << "$trix-icon-shapes: (\n"
    icon_names.each do |name, gem_name|
      shape = BootstrapIcons::BootstrapIcon.new(gem_name).path.gsub('"', "'").gsub(/\n\s*/, "")
      scss << "  \"#{name}\": \"#{shape}\",\n"
    end
    scss << ");\n"

    partial = Rails.root.join("app/assets/stylesheets/_trix_icon_shapes.scss")
    partial.write(scss) unless partial.exist? && partial.read == scss
  end
end

Rake::Task["dartsass:build"].enhance([ "dartsass:generate_trix_icon_shapes" ])
Rake::Task["dartsass:watch"].enhance([ "dartsass:generate_trix_icon_shapes" ])
