repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(md|markdown)$
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-merge-conflict
      - id: check-yaml
        args: ['--unsafe']

  - repo: local
    hooks:
      - id: rubocop
        name: rubocop
        entry: ./bin/rubocop
        language: system
        types: [ruby]
        args: ['--force-exclusion']
        require_serial: true
