company:
  name: TEST Company
  address: |
    Suedlandstrasse 33
    1040 Wien
    Austria
  vat_id: ATUxxxxxxx

fop:
  # Use podman wrapper (run script/setup-fop.sh first)
  binary_path: "./bin/abt-fop-container"

  # Debian trixie
  # binary_path: "./script/abt-fop"
