require 'test_helper'

class PageTitleTest < ActionDispatch::IntegrationTest
  def setup
    @issuer = IssuerCompany.get_the_issuer!
    @original_short_name = @issuer.short_name
  end

  def teardown
    # Restore original short_name after each test
    @issuer.update!(short_name: @original_short_name) if @issuer
  end

  test "home page shows dynamic title with issuer short_name" do
    @issuer.update!(short_name: "TestCorp")

    get root_path
    assert_response :success
    assert_select 'title', text: 'ABT: TestCorp'
  end

  test "home page shows ABT title when issuer short_name is blank" do
    # Temporarily set short_name to blank using update_column to bypass validation
    @issuer.update_column(:short_name, "")

    get root_path
    assert_response :success
    assert_select 'title', text: 'ABT'
  end

  test "favicon links are present in head" do
    get root_path
    assert_response :success
    # Check for SVG favicon (generated by Rails favicon_link_tag)
    assert_select 'link[rel="icon"][type="image/svg+xml"]'
    # Check for ICO favicon (manual link tag)
    assert_select 'link[rel="icon"][type="image/x-icon"][href="/favicon.ico"]'
  end
end