require "application_system_test_case"

class EmailPreviewTest < ApplicationSystemTestCase
  setup do
    @invoice = invoices(:published_invoice)
    @delivery_note = delivery_notes(:published_delivery_note)
  end

  test "email preview URLs use correct paths for subdirectory deployment" do
    visit invoice_path(@invoice)

    email_wrapper = find("[data-controller='generic-email-preview']")

    preview_url = email_wrapper["data-generic-email-preview-preview-url-value"]
    raw_preview_url = email_wrapper["data-generic-email-preview-raw-preview-url-value"]
    send_url = email_wrapper["data-generic-email-preview-send-url-value"]

    # URLs should be generated by Rails path helpers that respect subdirectory deployment
    assert_equal preview_email_invoice_path(@invoice), preview_url
    assert_equal preview_email_raw_invoice_path(@invoice), raw_preview_url
    assert_equal send_email_invoice_path(@invoice), send_url

    assert_includes preview_url, @invoice.id.to_s, "Preview URL should contain invoice ID"
    assert_includes raw_preview_url, @invoice.id.to_s, "Raw preview URL should contain invoice ID"
    assert_includes send_url, @invoice.id.to_s, "Send URL should contain invoice ID"
    assert_includes preview_url, "preview_email", "Preview URL should contain preview_email action"
    assert_includes raw_preview_url, "preview_email_raw", "Raw preview URL should contain preview_email_raw action"
    assert_includes send_url, "send_email", "Send URL should contain send_email action"
  end

  test "invoice email preview iframe renders styled email body under strict CSP" do
    visit invoice_path(@invoice)

    click_on "Send E-Mail"

    iframe_element = find("iframe.email-preview-iframe", wait: 5)

    within_frame(iframe_element) do
      assert_text "Dear #{@invoice.customer.name}", wait: 5
      # The mailer layout sets body { background-color: #f8f9fa } via an inline
      # <style> block. If CSP blocks it the body stays transparent — this
      # assertion guards against the auto-nonced style-src directive overriding
      # 'unsafe-inline'.
      bg = page.evaluate_script("getComputedStyle(document.body).backgroundColor")
      assert_equal "rgb(248, 249, 250)", bg, "Inline <style> from mailer layout should be applied in iframe"
    end
  end

  test "post-publish banner strips the published query param so reloads don't re-trigger auto-download" do
    visit invoice_path(@invoice, published: 1)
    assert_selector ".alert-success", text: "booked"
    assert_current_path invoice_path(@invoice), wait: 2
  end
end
