require "test_helper"

class EmailPreviewTest < ActionDispatch::SystemTestCase
  setup do
    @invoice = invoices(:published_invoice)
    @delivery_note = delivery_notes(:published_delivery_note)
  end

  test "email preview URLs use correct paths for subdirectory deployment" do
    visit invoice_path(@invoice)

    # Check that email preview wrapper has correct URL data attributes
    email_wrapper = find('.email-preview-wrapper')

    preview_url = email_wrapper['data-email-preview-preview-url-value']
    send_url = email_wrapper['data-email-preview-send-url-value']

    # URLs should be generated by Rails path helpers that respect subdirectory deployment
    assert_equal preview_email_invoice_path(@invoice), preview_url
    assert_equal send_email_invoice_path(@invoice), send_url

    # URLs should contain the invoice ID and be properly formed
    assert_includes preview_url, @invoice.id.to_s, "Preview URL should contain invoice ID"
    assert_includes send_url, @invoice.id.to_s, "Send URL should contain invoice ID"
    assert_includes preview_url, "preview_email", "Preview URL should contain preview_email action"
    assert_includes send_url, "send_email", "Send URL should contain send_email action"
  end

  test "delivery note email preview URLs use correct paths for subdirectory deployment" do
    visit delivery_note_path(@delivery_note)

    # Check that email preview wrapper has correct URL data attributes
    email_wrapper = find('.email-delivery_note-preview-wrapper')

    preview_url = email_wrapper['data-delivery-note-email-preview-preview-url-value']
    send_url = email_wrapper['data-delivery-note-email-preview-send-url-value']

    # URLs should be generated by Rails path helpers that respect subdirectory deployment
    assert_equal preview_email_delivery_note_path(@delivery_note), preview_url
    assert_equal send_email_delivery_note_path(@delivery_note), send_url

    # URLs should contain the delivery note ID and be properly formed
    assert_includes preview_url, @delivery_note.id.to_s, "Preview URL should contain delivery note ID"
    assert_includes send_url, @delivery_note.id.to_s, "Send URL should contain delivery note ID"
    assert_includes preview_url, "preview_email", "Preview URL should contain preview_email action"
    assert_includes send_url, "send_email", "Send URL should contain send_email action"
  end
end
